name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just install

      - name: Format and lint
        run: just format

  test:
    name: test ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just install
    
      - name: Run Python tests
        run: uv run pytest

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6

      - name: Install just
        uses: extractions/setup-just@v2
        
      - name: Install the project
        run: just install

      - name: Build with MkDocs
        run: uv run mkdocs build

  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6

      - name: Install just
        uses: extractions/setup-just@v2
        
      - run: uv build

  ci-success:
    needs: [format-and-lint, test, build-docs, build-package]
    runs-on: ubuntu-latest
    steps:
      - name: CI Success
        run: echo "All CI checks passed!"
